# Generated by Django 4.2.4 on 2023-08-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
